print(3 + 4)
print(3 - 4)
print(3 * 4)
print(3 / 4)
print(3 % 4)
print(3 ** 4)
print(3 // 4)
#printing strings
print("Tamanna")
print("Gupta")
print("India")
print("I am enjoying 30 days of python")

print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4-4j))
print(type(['Asabeneh', 'Python', 'Finland']))
print(type("tamanna"))
print(type("gupta"))
print(type("india"))